workflows:
  default:
    name: Default Workflow
    environment:
      flutter: stable
      node: 16
      xcode: 14
      android:
        sdk: latest
      ios:
        xcode: 14
    scripts:
      - name: Install Dependencies
        script: |
          # Install dependencies for React Native
          yarn install
      - name: Build Android
        script: |
          # Build the Android app
          npx react-native run-android --variant=release
      - name: Build iOS
        script: |
          # Build the iOS app
          npx react-native run-ios --configuration Release
    artifacts:
      - build/**/*
